version: '3.9'
services:
  movie-session-service:
    build: .
    restart: on-failure
    ports:
      - '3000:3000'
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - default
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - MONGO_ADDRESS=mongodb://mongo:27017/movie-session-db
      - MOVIE_SERVICE_URL=http://host.docker.internal:8080/api/movie

  mongo:
    image: mongo:8.0.4
    ports:
      - '27018:27017'
    volumes:
      - ./docker/data/mongo/db:/data/db
    networks:
      - default
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    driver: bridge